- hosts: web2
  user: root
  sudo: yes
  tasks:
  - name: Create multiple directories
    file:
      path: "{{ item }}"
      state: directory
#    register: file_details
    with_items: 
        - '/tmp/devops1'
        - '/tmp/devops3'

 # - debug:
 #     msg: "The file or directory exists"
 #   when: file_details.stat.exists
