- hosts: web2
  user: root
  sudo: yes
  tasks:
  - name: create dir
    file:
     path: /tmp/devops2
     state: directory

  - name: Create multiple directories
    stat:
      path: /tmp/devops2
  #    state: directory
    register: file_details


  - debug:
      msg: "The file or directory exists"
    when: file_details.stat.exists

